version: '3'

services:
  postgres:
    image: openmaptiles/postgis
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=gis
      - POSTGRES_PASSWORD=gis
    ports: 
      - "5432:5432"

volumes: 
  pgdata:
